Switch from scss to tailwind
Vearso/nie-pyszne-pl pull request #17
Opened 2021-01-18 14:02 UTC by foxy-methoxy

2021-01-18 15:01 UTC, kevinikos requested changes

2021-01-18 15:01 UTC, kevinikos commented on src/components/Products/ProductsList.vue
> +    <strong>Product list is empty</strong>
use translation instead of plain text

2021-01-18 15:01 UTC, kevinikos commented on src/components/Products/ProductsListItem.vue
> +         :style="{ backgroundImage: 'url(' + imgUrl + ')' }"></div>
align attributes and add line break before next html element

2021-01-18 15:01 UTC, kevinikos commented on src/components/Products/ProductsListItem.vue
> +			<span>{{ rating }} </span>
remove whitespace between text and closing `span` tag

2021-01-18 15:01 UTC, kevinikos commented on src/components/Products/ProductsListItem.vue
> +	computed: {
you should move `computed` to `setup` function which is part of `vue-composition-api` feature,
also if you want to use something like `mapGetters` you can check `vue-composition-helpers`
https://github.com/greenpress/vuex-composition-helpers

2021-01-18 15:01 UTC, kevinikos commented on src/components/Products/ProductsListItem.vue
>  export default {
use `defineComponent({...})` instead of `{...}`

2021-01-18 15:30 UTC, foxy-methoxy commented on src/components/Products/ProductsListItem.vue
> +
w webstormie wyswietlaja sie dobrze wciecia?

2021-01-19 11:55 UTC, entrop- approved these changes

2021-01-19 12:25 UTC, merged