Product list
Vearso/nie-pyszne-pl pull request #5
Opened 2021-01-13 12:29 UTC by foxy-methoxy

2021-01-13 13:12 UTC, entrop- commented on src/components/Products/ProductsListItem.vue
> +      <span class="product-list-item__description__title" v-if="name.length >= 20">{{ name.substring(0,14).concat("..") }} </span>
you can use v-else in regard to previous line
just change v-if="name.length >= 20" to v-else

2021-01-13 13:12 UTC, entrop- commented on src/store/modules/cart.ts
> +    console.log(getters.cartItems(state));
dont leave console.logs in pushed code

2021-01-13 13:12 UTC, entrop- commented on src/components/Products/ProductsList.vue
> +      v-for="(item, index) in items"
what if items are empty? searching for object attributes (like .name below) will cause errors
its easly fixed when you can add v-if="items" for whole component so it only renders when list is here

2021-01-13 13:12 UTC, entrop- commented on src/components/Products/ProductsListItem.vue
> +.product-list-item {
tailwind?

2021-01-13 13:36 UTC, KamilWozniak requested changes

2021-01-13 13:36 UTC, KamilWozniak commented on src/components/Products/ProductsList.vue
> +    v-bind:style="[
taka podpowiedź: wystarczy sam dwukropek `:style` zamiast całego `v-bind:style` :)

2021-01-13 13:36 UTC, KamilWozniak commented on src/components/Products/ProductsList.vue
> +        : 'grid-template-columns: 1fr 1fr 1fr'
czemu tak a nie po prostu `'grid-template-columns: 1fr 1fr 1fr'`?

2021-01-13 13:36 UTC, KamilWozniak commented on src/components/Products/ProductsListItem.vue
> +      <span class="product-list-item__description__title" v-if="name.length < 20">{{ name }} </span>
raz masz po jednym propie w linii, raz wszystkie w linii. Trzeba to ujednolicić. Najlepiej po jednym propie na linie

2021-01-13 13:36 UTC, KamilWozniak commented on src/components/Products/ProductsListItem.vue
> +    border-radius: 2rem 0 2rem 0;
można to zapisać `border-radius: 2rem 0`;

2021-01-13 13:36 UTC, KamilWozniak commented on src/store/modules/cart.ts
> +    const cartItem = state.items.find(product => product.id === item.id);
cartItem: CartItem | undefined

2021-01-13 13:47 UTC, foxy-methoxy commented on src/components/Products/ProductsList.vue
> +        : 'grid-template-columns: 1fr 1fr 1fr'
hardcoded tymczasowo, dopóki nie będzie z menu wybranej opcji czy ma byc wyswietlane w formie listy czy w formie kafelkow

2021-01-14 08:24 UTC, entrop- approved these changes

2021-01-14 08:30 UTC, merged